behaviors:
  Seeker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 50
      buffer_size: 500
      learning_rate: 0.0003
      beta: 1e-2
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 50
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000000
    time_horizon: 1024
    summary_freq: 50000