training_steps: 1000000
observation_size: 3
action_dim: 5
hidden_size: 516
learning_rate: 0.0001
agent_id_a: 0
agent_id_b: 1
no_agents: 2
buffer_size: 1024
batch_size: 1024
update_period: 1024
gamma: 0.00
tau: 0.995
alpha: 0.2
unity_environment: "C:\\Users\\rmarr\\Documents\\ml-agents-dodgeball-env-ICT"
no_simulations: 1
time_scale: 2.0
wandb_log: True