behaviors:
  AgentA:
    trainer_type: sac
    summary_freq: 5000
    time_horizon: 64
    max_steps: 500000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    init_path: null
    threaded: false
    hyperparameters:
      # sac specific
      buffer_init_steps: 1000
      init_entcoef: 1
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
      #default
      learning_rate: 0.0003
      batch_size: 1024
      buffer_size: 10240
      learning_rate_schedule: constant
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: false
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
        network_settings:
          hidden_units: 128
          num_layers: 2
          normalize: false
          vis_encode_type: simple
          conditioning_type: hyper
    self_play:
      save_steps: 50000
      team_change: 1000000
      swap_steps: 200000
      play_against_latest_model_ratio: 0.5
      window: 100
      initial_elo: 1200

  AgentB:
    trainer_type: sac
    summary_freq: 5000
    time_horizon: 64
    max_steps: 500000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    init_path: null
    threaded: false
    hyperparameters:
      # sac specific
      buffer_init_steps: 1000
      init_entcoef: 1
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
      #default
      learning_rate: 0.0003
      batch_size: 1024
      buffer_size: 10240
      learning_rate_schedule: constant
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: false
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
        network_settings:
          hidden_units: 128
          num_layers: 2
          normalize: false
          vis_encode_type: simple
          conditioning_type: hyper
    self_play:
      save_steps: 50000
      team_change: 1000000
      swap_steps: 200000
      play_against_latest_model_ratio: 0.5
      window: 100
      initial_elo: 1200
